/*
 * Onboarding API
 *  The onboarding API allows you to refer your customers and personal contacts to Brex. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: developer-access@brex.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.BeneficialOwnerAddress;
import com.konfigthis.client.model.BeneficialOwnerIdentityDocument;
import com.konfigthis.client.model.CompanyRelationship;
import com.konfigthis.client.model.Prong;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.LocalDate;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for BeneficialOwner
 */
public class BeneficialOwnerTest {
    private final BeneficialOwner model = new BeneficialOwner();

    /**
     * Model tests for BeneficialOwner
     */
    @Test
    public void testBeneficialOwner() {
        // TODO: test BeneficialOwner
    }

    /**
     * Test the property 'legalName'
     */
    @Test
    public void legalNameTest() {
        // TODO: test legalName
    }

    /**
     * Test the property 'companyRelationship'
     */
    @Test
    public void companyRelationshipTest() {
        // TODO: test companyRelationship
    }

    /**
     * Test the property 'dateOfBirth'
     */
    @Test
    public void dateOfBirthTest() {
        // TODO: test dateOfBirth
    }

    /**
     * Test the property 'identityDocument'
     */
    @Test
    public void identityDocumentTest() {
        // TODO: test identityDocument
    }

    /**
     * Test the property 'address'
     */
    @Test
    public void addressTest() {
        // TODO: test address
    }

    /**
     * Test the property 'prong'
     */
    @Test
    public void prongTest() {
        // TODO: test prong
    }

}
