/*
 * Onboarding API
 *  The onboarding API allows you to refer your customers and personal contacts to Brex. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: developer-access@brex.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.BeneficialOwner;
import com.konfigthis.client.model.BeneficialOwnerAddress;
import com.konfigthis.client.model.IncorporationType;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for CreateReferralRequestBusiness
 */
public class CreateReferralRequestBusinessTest {
    private final CreateReferralRequestBusiness model = new CreateReferralRequestBusiness();

    /**
     * Model tests for CreateReferralRequestBusiness
     */
    @Test
    public void testCreateReferralRequestBusiness() {
        // TODO: test CreateReferralRequestBusiness
    }

    /**
     * Test the property 'legalName'
     */
    @Test
    public void legalNameTest() {
        // TODO: test legalName
    }

    /**
     * Test the property 'incorporationType'
     */
    @Test
    public void incorporationTypeTest() {
        // TODO: test incorporationType
    }

    /**
     * Test the property 'employerIdentificationNumber'
     */
    @Test
    public void employerIdentificationNumberTest() {
        // TODO: test employerIdentificationNumber
    }

    /**
     * Test the property 'websiteUrl'
     */
    @Test
    public void websiteUrlTest() {
        // TODO: test websiteUrl
    }

    /**
     * Test the property 'activityDescription'
     */
    @Test
    public void activityDescriptionTest() {
        // TODO: test activityDescription
    }

    /**
     * Test the property 'address'
     */
    @Test
    public void addressTest() {
        // TODO: test address
    }

    /**
     * Test the property 'beneficialOwners'
     */
    @Test
    public void beneficialOwnersTest() {
        // TODO: test beneficialOwners
    }

    /**
     * Test the property 'alternateAddress'
     */
    @Test
    public void alternateAddressTest() {
        // TODO: test alternateAddress
    }

}
