/*
 * Onboarding API
 *  The onboarding API allows you to refer your customers and personal contacts to Brex. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: developer-access@brex.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.Applicant;
import com.konfigthis.client.model.ContactPreference;
import com.konfigthis.client.model.CreateReferralRequestBusiness;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for CreateReferralRequest
 */
public class CreateReferralRequestTest {
    private final CreateReferralRequest model = new CreateReferralRequest();

    /**
     * Model tests for CreateReferralRequest
     */
    @Test
    public void testCreateReferralRequest() {
        // TODO: test CreateReferralRequest
    }

    /**
     * Test the property 'referralCode'
     */
    @Test
    public void referralCodeTest() {
        // TODO: test referralCode
    }

    /**
     * Test the property 'applicant'
     */
    @Test
    public void applicantTest() {
        // TODO: test applicant
    }

    /**
     * Test the property 'business'
     */
    @Test
    public void businessTest() {
        // TODO: test business
    }

    /**
     * Test the property 'contactPreference'
     */
    @Test
    public void contactPreferenceTest() {
        // TODO: test contactPreference
    }

}
