/*
 * Onboarding API
 *  The onboarding API allows you to refer your customers and personal contacts to Brex. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: developer-access@brex.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for DomesticInstruction
 */
public class DomesticInstructionTest {
    private final DomesticInstruction model = new DomesticInstruction();

    /**
     * Model tests for DomesticInstruction
     */
    @Test
    public void testDomesticInstruction() {
        // TODO: test DomesticInstruction
    }

    /**
     * Test the property 'accountType'
     */
    @Test
    public void accountTypeTest() {
        // TODO: test accountType
    }

    /**
     * Test the property 'bankAccountNumber'
     */
    @Test
    public void bankAccountNumberTest() {
        // TODO: test bankAccountNumber
    }

    /**
     * Test the property 'bankRoutingNumber'
     */
    @Test
    public void bankRoutingNumberTest() {
        // TODO: test bankRoutingNumber
    }

    /**
     * Test the property 'beneficiaryName'
     */
    @Test
    public void beneficiaryNameTest() {
        // TODO: test beneficiaryName
    }

    /**
     * Test the property 'beneficiaryAddress'
     */
    @Test
    public void beneficiaryAddressTest() {
        // TODO: test beneficiaryAddress
    }

    /**
     * Test the property 'bankName'
     */
    @Test
    public void bankNameTest() {
        // TODO: test bankName
    }

    /**
     * Test the property 'bankAddress'
     */
    @Test
    public void bankAddressTest() {
        // TODO: test bankAddress
    }

}
