/*
 * Onboarding API
 *  The onboarding API allows you to refer your customers and personal contacts to Brex. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: developer-access@brex.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.annotations.ApiModel;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Relationship of this beneficial owner for this company.
 */
@JsonAdapter(CompanyRelationship.Adapter.class)public enum CompanyRelationship {
  
  FOUNDER("FOUNDER"),
  
  EXECUTIVE("EXECUTIVE"),
  
  SENIOR_LEADERSHIP("SENIOR_LEADERSHIP"),
  
  OTHER("OTHER");

  private String value;

  CompanyRelationship(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static CompanyRelationship fromValue(String value) {
    for (CompanyRelationship b : CompanyRelationship.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<CompanyRelationship> {
    @Override
    public void write(final JsonWriter jsonWriter, final CompanyRelationship enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public CompanyRelationship read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return CompanyRelationship.fromValue(value);
    }
  }
}

