/*
 * Onboarding API
 *  The onboarding API allows you to refer your customers and personal contacts to Brex. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: developer-access@brex.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.Applicant;
import com.konfigthis.client.model.ContactPreference;
import com.konfigthis.client.model.CreateReferralRequestBusiness;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * Submit a new referral to Brex for onboarding.
 */
@ApiModel(description = "Submit a new referral to Brex for onboarding.")@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class CreateReferralRequest {
  public static final String SERIALIZED_NAME_REFERRAL_CODE = "referral_code";
  @SerializedName(SERIALIZED_NAME_REFERRAL_CODE)
  private String referralCode;

  public static final String SERIALIZED_NAME_APPLICANT = "applicant";
  @SerializedName(SERIALIZED_NAME_APPLICANT)
  private Applicant applicant;

  public static final String SERIALIZED_NAME_BUSINESS = "business";
  @SerializedName(SERIALIZED_NAME_BUSINESS)
  private CreateReferralRequestBusiness business;

  public static final String SERIALIZED_NAME_CONTACT_PREFERENCE = "contact_preference";
  @SerializedName(SERIALIZED_NAME_CONTACT_PREFERENCE)
  private ContactPreference contactPreference;

  public CreateReferralRequest() {
  }

  public CreateReferralRequest referralCode(String referralCode) {
    
    
    
    
    this.referralCode = referralCode;
    return this;
  }

   /**
   * Referral code that attributes credit to you if the prospect signs up for a Brex account.
   * @return referralCode
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "Referral code that attributes credit to you if the prospect signs up for a Brex account.")

  public String getReferralCode() {
    return referralCode;
  }


  public void setReferralCode(String referralCode) {
    
    
    
    this.referralCode = referralCode;
  }


  public CreateReferralRequest applicant(Applicant applicant) {
    
    
    
    
    this.applicant = applicant;
    return this;
  }

   /**
   * Get applicant
   * @return applicant
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public Applicant getApplicant() {
    return applicant;
  }


  public void setApplicant(Applicant applicant) {
    
    
    
    this.applicant = applicant;
  }


  public CreateReferralRequest business(CreateReferralRequestBusiness business) {
    
    
    
    
    this.business = business;
    return this;
  }

   /**
   * Get business
   * @return business
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public CreateReferralRequestBusiness getBusiness() {
    return business;
  }


  public void setBusiness(CreateReferralRequestBusiness business) {
    
    
    
    this.business = business;
  }


  public CreateReferralRequest contactPreference(ContactPreference contactPreference) {
    
    
    
    
    this.contactPreference = contactPreference;
    return this;
  }

   /**
   * Get contactPreference
   * @return contactPreference
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public ContactPreference getContactPreference() {
    return contactPreference;
  }


  public void setContactPreference(ContactPreference contactPreference) {
    
    
    
    this.contactPreference = contactPreference;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the CreateReferralRequest instance itself
   */
  public CreateReferralRequest putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateReferralRequest createReferralRequest = (CreateReferralRequest) o;
    return Objects.equals(this.referralCode, createReferralRequest.referralCode) &&
        Objects.equals(this.applicant, createReferralRequest.applicant) &&
        Objects.equals(this.business, createReferralRequest.business) &&
        Objects.equals(this.contactPreference, createReferralRequest.contactPreference)&&
        Objects.equals(this.additionalProperties, createReferralRequest.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(referralCode, applicant, business, contactPreference, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateReferralRequest {\n");
    sb.append("    referralCode: ").append(toIndentedString(referralCode)).append("\n");
    sb.append("    applicant: ").append(toIndentedString(applicant)).append("\n");
    sb.append("    business: ").append(toIndentedString(business)).append("\n");
    sb.append("    contactPreference: ").append(toIndentedString(contactPreference)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("referral_code");
    openapiFields.add("applicant");
    openapiFields.add("business");
    openapiFields.add("contact_preference");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("referral_code");
    openapiRequiredFields.add("applicant");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to CreateReferralRequest
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!CreateReferralRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in CreateReferralRequest is not found in the empty JSON string", CreateReferralRequest.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : CreateReferralRequest.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      if (!jsonObj.get("referral_code").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `referral_code` to be a primitive type in the JSON string but got `%s`", jsonObj.get("referral_code").toString()));
      }
      // validate the required field `applicant`
      Applicant.validateJsonObject(jsonObj.getAsJsonObject("applicant"));
      // validate the optional field `business`
      if (jsonObj.get("business") != null && !jsonObj.get("business").isJsonNull()) {
        CreateReferralRequestBusiness.validateJsonObject(jsonObj.getAsJsonObject("business"));
      }
      // validate the optional field `contact_preference`
      if (jsonObj.get("contact_preference") != null && !jsonObj.get("contact_preference").isJsonNull()) {
        ContactPreference.validateJsonObject(jsonObj.getAsJsonObject("contact_preference"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!CreateReferralRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'CreateReferralRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<CreateReferralRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(CreateReferralRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<CreateReferralRequest>() {
           @Override
           public void write(JsonWriter out, CreateReferralRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public CreateReferralRequest read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             CreateReferralRequest instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of CreateReferralRequest given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of CreateReferralRequest
  * @throws IOException if the JSON string is invalid with respect to CreateReferralRequest
  */
  public static CreateReferralRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, CreateReferralRequest.class);
  }

 /**
  * Convert an instance of CreateReferralRequest to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

