/*
 * Onboarding API
 *  The onboarding API allows you to refer your customers and personal contacts to Brex. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: developer-access@brex.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.annotations.ApiModel;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Incorporation type of the company referred.
 */
@JsonAdapter(IncorporationType.Adapter.class)public enum IncorporationType {
  
  C_CORP("C_CORP"),
  
  S_CORP("S_CORP"),
  
  B_CORP("B_CORP"),
  
  LLC("LLC"),
  
  LLP("LLP"),
  
  SOLE_PROP("SOLE_PROP"),
  
  ORG_501C3("ORG_501C3"),
  
  LP("LP");

  private String value;

  IncorporationType(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static IncorporationType fromValue(String value) {
    for (IncorporationType b : IncorporationType.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<IncorporationType> {
    @Override
    public void write(final JsonWriter jsonWriter, final IncorporationType enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public IncorporationType read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return IncorporationType.fromValue(value);
    }
  }
}

