/*
 * Onboarding API
 *  The onboarding API allows you to refer your customers and personal contacts to Brex. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: developer-access@brex.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.annotations.ApiModel;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Status of the referral. &#x60;UNCLAIMED&#x60; or &#x60;EXPIRED&#x60; unless the customer completes signup. Customers are attributed once &#x60;ACTIVE&#x60; until the account is &#x60;CLOSED&#x60;.
 */
@JsonAdapter(ReferralStatus.Adapter.class)public enum ReferralStatus {
  
  UNCLAIMED("UNCLAIMED"),
  
  EXPIRED("EXPIRED"),
  
  ACTIVE("ACTIVE"),
  
  CLOSED("CLOSED");

  private String value;

  ReferralStatus(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static ReferralStatus fromValue(String value) {
    for (ReferralStatus b : ReferralStatus.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<ReferralStatus> {
    @Override
    public void write(final JsonWriter jsonWriter, final ReferralStatus enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public ReferralStatus read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return ReferralStatus.fromValue(value);
    }
  }
}

